"""empty message

Revision ID: 4d66bddf91c2
Revises: baab3efe5dd2
Create Date: 2023-04-18 18:22:57.246470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d66bddf91c2'
down_revision = 'baab3efe5dd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
