"""empty message

Revision ID: 9daf0ba6d882
Revises: 
Create Date: 2023-04-28 00:13:12.331969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9daf0ba6d882'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('surname', sa.String(length=128), nullable=True),
    sa.Column('birth_data', sa.Date(), nullable=True),
    sa.Column('death_data', sa.Date(), nullable=True),
    sa.Column('sity', sa.String(length=128), nullable=False),
    sa.Column('photo', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relatives_id'), 'relatives', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('telegram', sa.String(length=128), nullable=True),
    sa.Column('vk', sa.String(length=128), nullable=True),
    sa.Column('method', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_hashed_password'), 'user', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('link',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('relatives_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['relatives_id'], ['relatives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'relatives_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_hashed_password'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_relatives_id'), table_name='relatives')
    op.drop_table('relatives')
    # ### end Alembic commands ###
